version: '3'

services:

  vakhyash-api:
    container_name: vakhyash-api
    image: gcr.io/ekstepspeechrecognition/speech_recognition_model_api:3.2.37
    environment:
      - gpu=true
    volumes:
      - $PWD/api/deployed_models/:/opt/speech_recognition_open_api/deployed_models/

  vakhyash-proxy:
    container_name: vakhyash-proxy
    image: gcr.io/ekstepspeechrecognition/speech_recognition_model_api_proxy:1.0.4
    ports:
      - 8091:9009
    depends_on:
      - vakhyash-api
    volumes:
      - $PWD/proxy/deployed_models/:/opt/speech_recognition_open_api_proxy/deployed_models/

networks:
  default:
    name: bahmni-docker_default
    external: true
